[project]
name = "catechismmanagementsystem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.5",
    "dependency-injector>=4.49.1",
    "fastapi[standard]>=0.139.2",
    "logto>=0.2.1",
    "psycopg[binary,pool]>=3.3.4",
    "pyjwt[crypto]>=2.13.0",
    "sqlalchemy>=2.0.51",
]

[tool.uv.workspace]
members = [
    "apps/cms_admin_dashboard_api",
    "apps/cms_db_ops",
    "libs/cms_db_models",
    "libs/cms_common",
    "libs/cms_integrations",
    "libs/cms_locale",
]

[dependency-groups]
dev = [
    "ruff>=0.15.22",
]
