"""add unit

Revision ID: 68d4bdcf0877
Revises: da55ab1dcb77
Create Date: 2026-08-29 19:06:57.770349

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68d4bdcf0877"
down_revision: Union[str, Sequence[str], None] = "da55ab1dcb77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "units",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("grade_id", sa.Uuid(), nullable=False),
        sa.Column("study_year_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "created_by", sa.String(length=20), server_default="system", nullable=False
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_by", sa.String(length=20), server_default="system", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["grade_id"], ["study_year.grades.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["study_year_id"], ["study_year.study_years.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="study_year",
    )
    op.create_index(
        op.f("ix_study_year_units_code"),
        "units",
        ["code"],
        unique=True,
        schema="study_year",
    )
    op.create_index(
        op.f("ix_study_year_units_study_year_id"),
        "units",
        ["study_year_id"],
        unique=False,
        schema="study_year",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_study_year_units_study_year_id"),
        table_name="units",
        schema="study_year",
    )
    op.drop_index(
        op.f("ix_study_year_units_code"), table_name="units", schema="study_year"
    )
    op.drop_table("units", schema="study_year")
    # ### end Alembic commands ###
