"""schedule activity types add color and is system

Revision ID: 35a6c4023799
Revises: 377859954145
Create Date: 2026-09-14 15:37:51.260290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a6c4023799'
down_revision: Union[str, Sequence[str], None] = '377859954145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_activity_types', sa.Column('color', sa.String(length=7), nullable=True), schema='study_year')
    op.add_column('schedule_activity_types', sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False), schema='study_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_activity_types', 'is_system', schema='study_year')
    op.drop_column('schedule_activity_types', 'color', schema='study_year')
    # ### end Alembic commands ###
