"""add grade

Revision ID: 8329f4d04a2b
Revises: 0ac7521cac5c
Create Date: 2026-08-29 18:01:34.023556

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8329f4d04a2b"
down_revision: Union[str, Sequence[str], None] = "0ac7521cac5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grades",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("leader_catechist_id", sa.Uuid(), nullable=False),
        sa.Column("vice_leader_catechist_id", sa.Uuid(), nullable=False),
        sa.Column("secretary_catechist_id", sa.Uuid(), nullable=True),
        sa.Column("treasurer_catechist_id", sa.Uuid(), nullable=True),
        sa.Column("study_year_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "created_by", sa.String(length=20), server_default="system", nullable=False
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_by", sa.String(length=20), server_default="system", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["leader_catechist_id"], ["directory.catechists.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["secretary_catechist_id"], ["directory.catechists.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["study_year_id"], ["study_year.study_years.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["treasurer_catechist_id"], ["directory.catechists.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["vice_leader_catechist_id"],
            ["directory.catechists.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="study_year",
    )
    op.create_index(
        op.f("ix_study_year_grades_code"),
        "grades",
        ["code"],
        unique=True,
        schema="study_year",
    )
    op.create_index(
        op.f("ix_study_year_grades_study_year_id"),
        "grades",
        ["study_year_id"],
        unique=False,
        schema="study_year",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_study_year_grades_study_year_id"),
        table_name="grades",
        schema="study_year",
    )
    op.drop_index(
        op.f("ix_study_year_grades_code"), table_name="grades", schema="study_year"
    )
    op.drop_table("grades", schema="study_year")
    # ### end Alembic commands ###
