"""add unit students

Revision ID: 377859954145
Revises: 66eb5daf0b35
Create Date: 2026-08-29 22:43:49.995308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377859954145'
down_revision: Union[str, Sequence[str], None] = '66eb5daf0b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_students',
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['directory.students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['study_year.units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unit_id', 'student_id'),
    schema='study_year'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_students', schema='study_year')
    # ### end Alembic commands ###
