"""add study year table

Revision ID: 67cd9ab41acd
Revises: c6c4fa1407fa
Create Date: 2026-08-23 17:09:46.555517

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67cd9ab41acd"
down_revision: Union[str, Sequence[str], None] = "c6c4fa1407fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "study_years",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("code", sa.String(length=15), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("subject", sa.String(length=100), nullable=True),
        sa.Column("bible_sentence", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_readonly", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "created_by", sa.String(length=20), server_default="system", nullable=False
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_by", sa.String(length=20), server_default="system", nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="study_year",
    )
    op.create_index(
        op.f("ix_study_year_study_years_code"),
        "study_years",
        ["code"],
        unique=True,
        schema="study_year",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_study_year_study_years_code"),
        table_name="study_years",
        schema="study_year",
    )
    op.drop_table("study_years", schema="study_year")
    # ### end Alembic commands ###
