"""add basic catechist table

Revision ID: 4e1cdf6f496f
Revises: 
Create Date: 2026-08-01 14:20:08.359627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1cdf6f496f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catechists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('saint_name', sa.String(length=30), nullable=True),
    sa.Column('first_name', sa.String(length=10), nullable=False),
    sa.Column('middle_name', sa.String(length=25), nullable=True),
    sa.Column('last_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='directory'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catechists', schema='directory')
    # ### end Alembic commands ###
