"""add students

Revision ID: 66eb5daf0b35
Revises: c0c6864c55c6
Create Date: 2026-08-29 22:35:28.244054

"""
from typing import Sequence, Union

from sqlalchemy.dialects import postgresql

from alembic import op

import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '66eb5daf0b35'
down_revision: Union[str, Sequence[str], None] = 'c0c6864c55c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('saint_name', sa.String(length=30), nullable=True),
    sa.Column('first_name', sa.String(length=10), nullable=False),
    sa.Column('middle_name', sa.String(length=25), nullable=True),
    sa.Column('last_name', sa.String(length=10), nullable=False),
    sa.Column('gender', postgresql.ENUM(name='gender', create_type=False), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('student_status_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), server_default='system', nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=20), server_default='system', nullable=False),
    sa.ForeignKeyConstraint(['student_status_id'], ['directory.student_statuses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='directory'
    )
    op.create_index(op.f('ix_directory_students_code'), 'students', ['code'], unique=True, schema='directory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_directory_students_code'), table_name='students', schema='directory')
    op.drop_table('students', schema='directory')
    # ### end Alembic commands ###
