"""add catechists table

Revision ID: c6c4fa1407fa
Revises:
Create Date: 2026-08-12 17:47:29.995228

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6c4fa1407fa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catechists",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column(
            "title",
            sa.Enum(
                "MALE_CATECHIST",
                "FEMALE_CATECHIST",
                "NUN",
                "MONK",
                "FATHER",
                name="catechisttitle",
            ),
            nullable=False,
        ),
        sa.Column("saint_name", sa.String(length=30), nullable=True),
        sa.Column("first_name", sa.String(length=10), nullable=False),
        sa.Column("middle_name", sa.String(length=25), nullable=True),
        sa.Column("last_name", sa.String(length=10), nullable=False),
        sa.Column("gender", sa.Enum("MALE", "FEMALE", name="gender"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        schema="directory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("catechists", schema="directory")
    # ### end Alembic commands ###
