"""add unit catechists

Revision ID: 2b07c37ba843
Revises: 68d4bdcf0877
Create Date: 2026-08-29 22:24:52.306916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b07c37ba843'
down_revision: Union[str, Sequence[str], None] = '68d4bdcf0877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_catechists',
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('catechist_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['catechist_id'], ['directory.catechists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['study_year.units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unit_id', 'catechist_id'),
    schema='study_year'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_catechists', schema='study_year')
    # ### end Alembic commands ###
