"""add study year general schedule

Revision ID: 0ac7521cac5c
Revises: f0dd311ab419
Create Date: 2026-08-29 17:33:02.700821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ac7521cac5c"
down_revision: Union[str, Sequence[str], None] = "f0dd311ab419"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "general_schedules",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("start_at", sa.DateTime(), nullable=False),
        sa.Column("end_at", sa.DateTime(), nullable=True),
        sa.Column("schedule_activity_type_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column(
            "is_attendence_check", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("study_year_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "created_by", sa.String(length=20), server_default="system", nullable=False
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_by", sa.String(length=20), server_default="system", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["schedule_activity_type_id"],
            ["study_year.schedule_activity_types.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["study_year_id"], ["study_year.study_years.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="study_year",
    )
    op.create_index(
        op.f("ix_study_year_general_schedules_schedule_activity_type_id"),
        "general_schedules",
        ["schedule_activity_type_id"],
        unique=False,
        schema="study_year",
    )
    op.create_index(
        op.f("ix_study_year_general_schedules_study_year_id"),
        "general_schedules",
        ["study_year_id"],
        unique=False,
        schema="study_year",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_study_year_general_schedules_study_year_id"),
        table_name="general_schedules",
        schema="study_year",
    )
    op.drop_index(
        op.f("ix_study_year_general_schedules_schedule_activity_type_id"),
        table_name="general_schedules",
        schema="study_year",
    )
    op.drop_table("general_schedules", schema="study_year")
    # ### end Alembic commands ###
