[project]
name = "cms-admin-dashboard-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cms-common",
    "cms-integrations",
    "cms-locale",
    "dependency-injector",
    "fastapi[standard]",
    "logto",
    "pyjwt[crypto]",
]

[tool.uv.sources]
cms-common = { workspace = true }
cms-integrations = { workspace = true }
cms-locale = { workspace = true }
